[REF] mail_post_defer: adapt to upstream API change in assertNoMail
Fixes

```
2023-01-02 10:00:00,000 347 ERROR odoo odoo.addons.mail_post_defer.tests.test_mail: ERROR: MessagePostCase.test_model_without_threading
Traceback (most recent call last):
  File "/__w/mail/mail/mail_post_defer/tests/test_mail.py", line 213, in test_model_without_threading
    self.assertNoMail(self.partner_employee | self.partner_portal)
  File "/opt/odoo/addons/mail/tests/common.py", line 753, in assertNoMail
    self.assertNotSentEmail(recipients=recipients, message_id=mail_message.message_id)
AttributeError: 'NoneType' object has no attribute 'message_id'
```

Regression of https://github.com/odoo/odoo/pull/230766, fix proposed in https://github.com/odoo/odoo/pull/255720.